networks:
  monitorserv:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - --path.rootfs=/host
    pid: host
    restart: unless-stopped
    networks: [monitorserv]
    volumes:
      - /:/host:ro,rslave
    security_opt: ["no-new-privileges:true"]
    read_only: true
  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    networks: [monitorserv]
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks: [monitorserv]
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_EMAIL_PASSWORD=${GF_EMAIL_PASSWORD}
      - GF_EMAIL_HOST=${GF_EMAIL_HOST}
      - GF_EMAIL_USER=${GF_EMAIL_USER}
      - GF_EMAIL_PASSWORD=${GF_EMAIL_PASSWORD}
      - GF_EMAIL_FROM_ADDRESS=${GF_EMAIL_FROM_ADDRESS}
      - GF_EMAIL_FROM_NAME=${GF_EMAIL_FROM_NAME}
  blackbox:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    networks: [monitorserv]
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - --config.file=/etc/blackbox_exporter/config.yml
    restart: unless-stopped
  snmpexporter:
    image: prom/snmp-exporter:latest
    ports:
      - 9116:9116
    networks: [monitorserv]
