global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "node"
    static_configs:
      - targets:
          [
            "node-exporter:9100",
            "192.168.0.151:9100",
            "192.168.0.152:9100",
            "192.168.0.155:9100",
            "192.168.0.160:9100",
            "192.168.0.170:9100",
          ]
  - job_name: "blackbox"
    metrics_path: /probe
    static_configs:
      - targets:
          - https://saobentodosapucai.sp.gov.br
          - https://saobentodosapucai.1doc.com.br
          - https://saobento.amendolaeamendola.com.br:7443/sipweb/trabalhador/login/login.xhtml
          - https://saobento.amendolaeamendola.com.br/transparencia
          - https://saobento.amendolaeamendola.com.br/scpi9
          - https://saobento.amendolaeamendola.com.br/transparenciacamara
          - https://saobento.amendolaeamendola.com.br:8443/sipweb/trabalhador/login/login.xhtml
          - https://saobento.amendolaeamendola.com.br:8453/issweb/home
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
    params:
      module: [http_2xx]
  - job_name: "snmp"
    static_configs:
      - targets:
          - 192.168.0.1
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmpexporter:9116
